setup:
	sudo -H pip install pyspark
	sudo -H pip install jupyter
	sudo -H pip install pandas
	sudo -H pip install matplotlib
	sudo -H pip install seaborn
	sudo -H pip install -U numpy

run:setup
	jupyter notebook ./project.ipynb
	
