setup:
	sudo pip install pyspark
	sudo pip install jupyter
	sudo pip install pandas
	sudo pip install matplotlib
	sudo pip install seaborn
	sudo pip3 install -U numpy

run:setup
	jupyter notebook ./project.ipynb
	
